# Generated by Django 5.0.6 on 2024-06-08 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoadQuestApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.CharField(max_length=200)),
                ('end', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='TodoItem',
        ),
    ]
