# Generated by Django 5.0.6 on 2024-07-06 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoadQuestApp', '0005_remove_poi_amenities_remove_poi_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poi',
            name='type',
            field=models.CharField(max_length=100),
        ),
    ]
