# Generated by Django 5.0.6 on 2024-07-07 08:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoadQuestApp', '0006_alter_poi_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='poi',
            name='user_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='routeitem',
            name='user_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
