# Generated by Django 5.0.6 on 2024-08-20 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoadQuestApp', '0007_poi_user_id_routeitem_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poi',
            name='type',
            field=models.CharField(max_length=255),
        ),
    ]
