# Generated by Django 5.0.6 on 2024-08-18 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoadQuestApp', '0007_poi_user_id_routeitem_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='routeitem',
            name='stop1',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='routeitem',
            name='stop2',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='routeitem',
            name='stop3',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
