# Generated by Django 5.0.6 on 2024-08-20 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RoadQuestApp', '0008_alter_poi_type'),
        ('RoadQuestApp', '0009_alter_routeitem_stop1_alter_routeitem_stop2_and_more'),
    ]

    operations = [
    ]
